# Your project"s server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:

  release: "release"

  pages:
    - "src/pages/**/*"

  views:
    - "src/javascript/**/*.view.html"

  assets:
    - "src/assets/**/*"

  css:
    - "bower_components/angular-material/angular-material.css"
    - "bower_components/angular-material-data-table/dist/md-data-table.css"
    - "bower_components/angular-datepicker/dist/angular-datepicker.css"
    - "bower_components/angular-datepicker/dist/angular-datepicker.css"
    - "bower_components/angular-loading-bar/build/loading-bar.min.css"
    - "bower_components/fullcalendar/dist/fullcalendar.css"

  sass:
    - "src/sass/**/*.sass"

  javascriptAll:
    - "src/javascript/**/*"

  javascriptCustom:
    - "src/javascript/main.routes.js"
    - "src/javascript/main.module.js"
    - "src/javascript/**/*.value.js"
    - "src/javascript/**/*.filter.js"
    - "src/javascript/**/*.service.js"
    - "src/javascript/**/*.model.js"
    - "src/javascript/**/*.directive.js"
    - "src/javascript/**/*.controller.js"

  #Dependencies like jQuery, or Angular are brought in here
  # TODO: We need to see what we can delete from here
  javascriptVendor:
    - "bower_components/jquery/dist/jquery.min.js"
    - "bower_components/jquery-ui/jquery-ui.min.js"
    - "bower_components/angular/angular.min.js"
    - "bower_components/angular-sanitize/angular-sanitize.min.js"
    - "bower_components/angular-resource/angular-resource.min.js"
    - "bower_components/angular-animate/angular-animate.min.js"
    - "bower_components/angular-aria/angular-aria.min.js"
    - "bower_components/angular-material/angular-material.js"
    - "bower_components/angular-permission/dist/angular-permission.min.js"
    - "bower_components/angular-permission/dist/angular-permission-ui.min.js"
    - "bower_components/angular-messages/angular-messages.min.js"
    - "bower_components/angular-material-data-table/dist/md-data-table.min.js"
    - "bower_components/angular-ui-router/release/angular-ui-router.min.js"
    - "bower_components/moment/min/moment.min.js"
    - "bower_components/angular-moment/angular-moment.min.js"
    - "bower_components/ng-file-upload/ng-file-upload.min.js"
    - "bower_components/ngSelectable/src/ngSelectable.js"
    - "bower_components/underscore/underscore-min.js"
    - "bower_components/ng-csv/build/ng-csv.js"
    - "bower_components/angular-datepicker/dist/angular-datepicker.min.js"
    - "bower_components/angular-loading-bar/build/loading-bar.min.js"
    - "bower_components/angular-gravatar/build/angular-gravatar.js"
    - "bower_components/jQuery.print/jQuery.print.js"
    - "bower_components/alasql/dist/alasql.min.js"
    - "bower_components/js-xlsx/dist/xlsx.full.min.js"
    - "bower_components/angular-md5/angular-md5.min.js"
    - "bower_components/angular-ui-calendar/src/calendar.js"
    - "bower_components/fullcalendar/dist/fullcalendar.min.js"
    - "bower_components/fullcalendar/dist/gcal.js"
